### ISSUE TITLE
Rich Presence don't work if you have buttons and a party

### ISSUE THREAD

**Issue by aabssmc** [NepNep21/DiscordRPC4j16#1]
Not sure if this is a discord thing or this, but whenever you set buttons and set a party info+secrets, the presence doesn't show up

this is the code i used
```java
String partyid = UUID.randomUUID().toString().replaceAll("-", "");
String join = UUID.randomUUID().toString().replaceAll("-", "");
String match = UUID.randomUUID().toString().replaceAll("-", "");
RichPresence presence = new RichPresence.Builder()
        .addButton("test button", "https://google.com")
        .setPartyInfo(partyid, 1, 12)
        .setSecrets(join, null, match)
        .build();
client.sendPresence(presence);
```

Party infos and buttons work fine, but when you add the secrets it doesnt work

**Comment by NepNep21** [comment]
Seems to be a discord limitation, as adding an `onError` handler and printing `ErrorEvent#message` (a discord-provided message) shows "secrets cannot currently be sent with buttons".
