### ISSUE TITLE
asset doesnt work with data image url

### ISSUE THREAD

**Issue by aabssmc** [NepNep21/DiscordRPC4j16#2]
I tried setting the asset to a data image url `data:image/png;base64,iVBORw0KGgoAAAA...` and it didnt work, but i tried with a normal url and it worked

**Comment by NepNep21** [comment]
Is the use of a data url documented anywhere or supported by another library? I have never heard of discord supporting them.

**Comment by aabssmc** [comment]
i remember it working before, but then it just stopped working

**Comment by aabssmc** [comment]
unless im tripping im pretty sure they have support for data urls

**Comment by NepNep21** [comment]
Unless you can provide an example of it ever working, there isn't much I can do about it.

**Comment by NepNep21** [comment]
Closed unless the above is shown.
